### ISSUE TITLE
not working? or do i not know the steps 

### ISSUE THREAD

**Issue by memerontop** [Gumbobrot/Hazard-Token-Grabber-v2#13]
mind explaining the steps to me anyone? 

but so far ive done everything yet it seems to still not be working like whenever i click the set up thingy it js flashes then it deletes it's self

**Comment by Gumbobrot** [comment]
> mind explaining the steps to me anyone? 
> 
> but so far ive done everything yet it seems to still not be working like whenever i click the set up thingy it js flashes then it deletes it's self 

could you open up a terminal in the folder and then type setup.bat and show me the error..?

**Comment by memerontop** [comment]
![image](https://user-images.githubusercontent.com/127799720/227052738-57b76da9-e7d9-4317-a5e1-bb109f8b3ba2.png)

**Comment by memerontop** [comment]
that right?

**Comment by Gumbobrot** [comment]
is python installed on your machine? if yes try again with the latest version of the code which you can download [here](https://github.com/Gumbobrot/Hazard-Token-Grabber-v2/archive/refs/heads/main.zip/)
