### ISSUE TITLE
Failed to write your webhook to the src. Make sure the code is correct and has not been changed.

### ISSUE THREAD

**Issue by Bluenes** [Gumbobrot/Hazard-Token-Grabber-v2#19]
I enter my webhook and this is the error.

![image](https://github.com/Gumbobrot/Hazard-Token-Grabber-v2/assets/88560297/506ab7a7-8fb2-45f4-85d7-3856d9545295)

**Comment by Gumbobrot** [comment]
Download my code again and don't change anything in the src/main.py/hazard.py

**Comment by Bluenes** [comment]
Fixed it. My anti virus was detecting it and messed with it
