### ISSUE TITLE
monkey 2

### ISSUE THREAD

**Issue by DBright682** [Gumbobrot/Hazard-Token-Grabber-v2#4]
the script is unusable as it would appear the modules CANNOT be installed or imported how they are, and I don't have the patience to fix it......after 20 hours of making no progress in making this work with minimal changes, I'm just done.
That being said, it's still impressive work by all counts.

**Comment by qPhantasm** [comment]
send me the exact error

**Comment by qPhantasm** [comment]
probably a you-issue, for all the others it's working

**Comment by Gumbobrot** [comment]
try the latest vers

**Comment by Gumbobrot** [comment]
@DBright682
