### ISSUE TITLE
monkey 

### ISSUE THREAD

**Issue by KDot227** [Gumbobrot/Hazard-Token-Grabber-v2#6]
https://cheataway.com/invite

**Comment by Gumbobrot** [comment]
whats your problem man? havent checked the code?? "Made by Rdimo" i obv gave credits so js leave me alone bro and ofc i wouldnt even have to give creds i made my own builder and i will change much of the logger soon

**Comment by KDot227** [comment]
> whats your problem man? havent checked the code?? "Made by Rdimo" i obv gave credits so js leave me alone bro and ofc i wouldnt even have to give creds i made my own builder and i will change much of the logger soon

You literally removed his credit in the grab and put it your GitHub 💀💀💀

**Comment by Gumbobrot** [comment]
> > whats your problem man? havent checked the code?? "Made by Rdimo" i obv gave credits so js leave me alone bro and ofc i wouldnt even have to give creds i made my own builder and i will change much of the logger soon
> 
> You literally removed his credit in the grab and put it your GitHub 💀💀💀

are you dumb? I didn't? "Made by Rdimo" is in the fckng code

**Comment by KDot227** [comment]
![image](https://user-images.githubusercontent.com/110929758/216058184-c32ddfa0-cd83-4616-9258-1a0f00c9fe82.jpeg)

**Comment by Gumbobrot** [comment]
are you fricking dumb you Re using a that fckng outdated Version bro

**Comment by KDot227** [comment]
Also there isn't a reason to post this especially when he still makes updates to it in his server

**Comment by Gumbobrot** [comment]
> Also there isn't a reason to post this especially when he still makes updates to it in his server

he doesn't and as i fricking said I HAVE WRITTEN MY OWN FCKNG BUILDER

**Comment by KDot227** [comment]
> > Also there isn't a reason to post this especially when he still makes updates to it in his server
> 
> he doesn't and as i fricking said I HAVE WRITTEN MY OWN FCKNG BUILDER

He does and so what u made a builder 💀💀💀

**Comment by Gumbobrot** [comment]
bro why r u always hating! download the new version and check my builder! first: all is open sourced, second: im giving credits in the new version third: I made my own builder fourth: im just experienced python!!!

**Comment by KDot227** [comment]
> bro why r u always hating! download the new version and check my builder! first: all is open sourced, second: im giving credits in the new version third: I made my own builder fourth: im just experienced python!!!

1.) your just annoying
2.) Alr but why do you need a builder
3.) why builder if that's what the setup.bat file is for
4.) if your experienced in python you would make your own grabber that is better than his (not that hard)

**Comment by KDot227** [comment]
Bro ain't no way 💀💀💀
![image](https://user-images.githubusercontent.com/110929758/216068762-03473bab-68e3-4931-a838-0008ec1ca25e.png)

**Comment by Gumbobrot** [comment]
> Bro ain't no way 💀💀💀
> ![image](https://user-images.githubusercontent.com/110929758/216068762-03473bab-68e3-4931-a838-0008ec1ca25e.png)

I gave creds everywhere

**Comment by Gumbobrot** [comment]
> > bro why r u always hating! download the new version and check my builder! first: all is open sourced, second: im giving credits in the new version third: I made my own builder fourth: im just experienced python!!!
> 
> 1.) your just annoying
> 2.) Alr but why do you need a builder
> 3.) why builder if that's what the setup.bat file is for
> 4.) if your experienced in python you would make your own grabber that is better than his (not that hard)

sorry I meant experiencing my python skills, setup.bat is for requirements for builder

**Comment by 0x3C50** [comment]
jesus fucking christ dude just credit rdimo and move on

**Comment by Gumbobrot** [comment]
> jesus fucking christ dude just credit rdimo and move on

are you fricking dumb buddy check the code I fricking gave credits multiple times

**Comment by Gumbobrot** [comment]
if your brain Was big enough to check line 587 in the src/hazard.py you both would recognized how dumb you fucking are, just check the latest update idiot 🤦

**Comment by KDot227** [comment]
> if your brain Was big enough to check line 587 in the src/hazard.py you both would recognized how dumb you fucking are, just check the latest update idiot 🤦

Idc enough to check the code especially when it ain't even the actual version. You put a ss on the readme that showed it the other way so u still a skid lol

**Comment by Gumbobrot** [comment]
> > if your brain Was big enough to check line 587 in the src/hazard.py you both would recognized how dumb you fucking are, just check the latest update idiot 🤦
> 
> Idc enough to check the code especially when it ain't even the actual version. You put a ss on the readme that showed it the other way so u still a skid lol

bro thats a ss which I took like 3 months ago dumbass 🤦 too lazy to make a new one and idc about all your opinions, im giving credits mf

**Comment by KDot227** [comment]
> > > if your brain Was big enough to check line 587 in the src/hazard.py you both would recognized how dumb you fucking are, just check the latest update idiot 🤦
> > 
> > 
> > Idc enough to check the code especially when it ain't even the actual version. You put a ss on the readme that showed it the other way so u still a skid lol
> 
> bro thats a ss which I took like 3 months ago dumbass 🤦 too lazy to make a new one and idc about all your opinions, im giving credits mf

Still L skid + grabber repos smh

**Comment by Kyxnite** [comment]
You are retarded
